export const GMAIL_CLIENT_ID = process.env.GMAIL_CLIENT_ID;
export const GMAIL_CLIENT_SECRET = process.env.GMAIL_CLIENT_SECRET;
export const GMAIL_REFRESH_TOKEN = process.env.GMAIL_REFRESH_TOKEN;
export const POLLINATIONS_API_KEY = process.env.POLLINATIONS_API_KEY;
export const FOOTBALL_KEY_URL = process.env.FOOTBALL_KEY_URL;
export const TRENDS_KEY_URL = process.env.TRENDS_KEY_URL;
export const SLUG_KEY_URL = process.env.SLUG_KEY_URL;
export const ANYCRAWL_API_KEY = process.env.ANYCRAWL_API_KEY;
export const WATERCRAWL_API_KEY = process.env.WATERCRAWL_API_KEY;

// A static, Base64-encoded PNG of a classic football to be used as a fallback logo.
export const DEFAULT_FOOTBALL_LOGO_URI =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAdNSURBVHhe7ZxrbBTHfcaN6UhiCSQkCIIgCCQkCIIgCCQkCAAIvBIgCIIgCCQkCAAIvCIgCIIgCCQkCAAIvCIgCCQkCIIgCCQkCAAIvCIgCAIJIYSQgghJiIQISYgkRPi5mP/uu7O7M+e+d/d+V/Z+8UvOOffOmd2dnZn53ZmZmQnIysqye/fu0yVLlizp9/vLKyws/KFYLPb4sWPHXpcuXbpn8+bNu6hUKpcxDAvL5fJgYWGhWyaTvXF5eXl9+/btf8+bN++jQ4cOfcTHx28dOHDgVzEMD4jFYtI0zYBlWWQYBgZ5eXlIknTt/v37sSwLNpvNzUwmE9M0zWq1gsFgqFQqhmGorqoiSdKmaSAIAgRBkCSJBEEAGIZBkiQEQaAoCgCAJEkQBIGiKAACQBAURQEAQJAECIAgQRAAAAAAAAAAAAAAAAAAAAAAAP4/QfRkewdG4GgAAAAASUVORK5CYII=';
